pipeline{
    agent any
    stages{
        stage('Testing'){
            steps{
                script{
                    echo "Testing the application...."
                    echo "Executing pipeline for branch $BRANCH_NAME"
                }
                
            }
        }
        stage('build'){
            when {
                expression {
                    BRANCH_NAME == 'main'
                }
            }
        }
    }
}
